In [2]:
import numpy as np
ar=np.array([[1,2,3,4]])
ar

array([[1, 2, 3, 4]])

In [3]:
ar[0]

array([1, 2, 3, 4])

In [4]:
ar.shape

(1, 4)

In [5]:
ar[0,1]

2

In [6]:
ar[0,3]

4

In [7]:
lar = np.array([[1,4,6],[0,9,12],[9,7,4]])
lar

array([[ 1,  4,  6],
       [ 0,  9, 12],
       [ 9,  7,  4]])

In [8]:
lar.ndim

2

In [9]:
lar.diagonal()

array([1, 9, 4])

In [10]:
lar.diagonal(1)

array([ 4, 12])

In [11]:
lar.diagonal(2)

array([6])

In [12]:
three=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
three

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
three.diagonal()

array([[0, 6],
       [1, 7]])

In [14]:
lar.cumprod()

array([ 1,  4, 24,  0,  0,  0,  0,  0,  0], dtype=int32)

In [15]:
three.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [16]:
three.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [17]:
lar.cumsum()

array([ 1,  5, 11, 11, 20, 32, 41, 48, 52], dtype=int32)

In [18]:
lar.prod(0)

array([  0, 252, 288])

In [19]:
lar

array([[ 1,  4,  6],
       [ 0,  9, 12],
       [ 9,  7,  4]])

In [20]:
lar.prod(1)

array([ 24,   0, 252])

In [21]:
three.prod(0)

array([[ 0,  5],
       [12, 21]])

In [22]:
three

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
three.prod(1)

array([[ 0,  3],
       [24, 35]])

In [24]:
three.prod(2)

array([[ 0,  6],
       [20, 42]])

In [25]:
lar.ptp()

12

In [26]:
lar.max()

12

In [27]:
lar.max(0)

array([ 9,  9, 12])

In [28]:
lar.max(1)

array([ 6, 12,  9])

In [29]:
lar.min()

0

In [30]:
lar.min(0)

array([0, 4, 4])

In [31]:
lar.min(1)

array([1, 0, 4])

In [32]:
lar.ptp(0)

array([9, 5, 8])

In [33]:
three

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
lar.ptp(1)

array([ 5, 12,  5])

In [35]:
lar.std()

3.705184889007348

In [36]:
lar.mean()

5.777777777777778

In [37]:
lar.std(0)

array([4.02768199, 2.05480467, 3.39934634])

In [38]:
lar.var()

13.728395061728396

In [39]:
lar.T

array([[ 1,  0,  9],
       [ 4,  9,  7],
       [ 6, 12,  4]])

In [40]:
three.swapaxes(0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [41]:
three

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
lar.trace()

14

In [43]:
lar

array([[ 1,  4,  6],
       [ 0,  9, 12],
       [ 9,  7,  4]])

In [44]:
np.repeat(lar,2,axis=0)

array([[ 1,  4,  6],
       [ 1,  4,  6],
       [ 0,  9, 12],
       [ 0,  9, 12],
       [ 9,  7,  4],
       [ 9,  7,  4]])

In [45]:
np.repeat(lar,2)

array([ 1,  1,  4,  4,  6,  6,  0,  0,  9,  9, 12, 12,  9,  9,  7,  7,  4,
        4])

In [46]:
lar.std()

3.705184889007348

In [47]:
lar.std(0)

array([4.02768199, 2.05480467, 3.39934634])

In [48]:
lar.std(1)

array([2.05480467, 5.09901951, 2.05480467])

In [49]:
lar.var()

13.728395061728396

In [50]:
lar.var(0)

array([16.22222222,  4.22222222, 11.55555556])

In [51]:
lar.var(1)

array([ 4.22222222, 26.        ,  4.22222222])

In [52]:
lar.mean(1)

array([3.66666667, 7.        , 6.66666667])